-- ============================================================
-- ECM Homepage ACF Field Seeds
-- Target: wp_postmeta, post_id = 2 (homepage)
-- Run: mysql -u root -proot -P 10053 local < _seed-acf-homepage.sql
-- Uses INSERT IGNORE — safe to re-run; won't overwrite admin changes.
-- ============================================================

USE local;

INSERT IGNORE INTO wp_postmeta (post_id, meta_key, meta_value) VALUES

-- ── Trust Bar ────────────────────────────────────────────────────────────────
(2, 'trust_bar_text',    '✦ Trusted Care Matching · Free for Families - America\'s oldest and most respected Elder Care Directory'),
(2, '_trust_bar_text',   'field_ecm_trust_bar_text'),
(2, 'trust_bar_enabled', '1'),
(2, '_trust_bar_enabled','field_ecm_trust_bar_enabled'),

-- ── Navigation ───────────────────────────────────────────────────────────────
(2, 'nav_logo_alt',  'ElderCareMatters'),
(2, '_nav_logo_alt', 'field_ecm_nav_logo_alt'),

(2, 'nav_links',   '5'),
(2, '_nav_links',  'field_ecm_nav_links'),

(2, 'nav_links_0_label',   'How It Works'),
(2, '_nav_links_0_label',  'field_ecm_nav_link_label'),
(2, 'nav_links_0_url',     '#how-it-works'),
(2, '_nav_links_0_url',    'field_ecm_nav_link_url'),
(2, 'nav_links_0_is_cta',  '0'),
(2, '_nav_links_0_is_cta', 'field_ecm_nav_link_is_cta'),
(2, 'nav_links_0_new_tab', '0'),
(2, '_nav_links_0_new_tab','field_ecm_nav_link_new_tab'),

(2, 'nav_links_1_label',   'Find Care'),
(2, '_nav_links_1_label',  'field_ecm_nav_link_label'),
(2, 'nav_links_1_url',     '/find-care/'),
(2, '_nav_links_1_url',    'field_ecm_nav_link_url'),
(2, 'nav_links_1_is_cta',  '0'),
(2, '_nav_links_1_is_cta', 'field_ecm_nav_link_is_cta'),
(2, 'nav_links_1_new_tab', '0'),
(2, '_nav_links_1_new_tab','field_ecm_nav_link_new_tab'),

(2, 'nav_links_2_label',   'Resources'),
(2, '_nav_links_2_label',  'field_ecm_nav_link_label'),
(2, 'nav_links_2_url',     '/resources/'),
(2, '_nav_links_2_url',    'field_ecm_nav_link_url'),
(2, 'nav_links_2_is_cta',  '0'),
(2, '_nav_links_2_is_cta', 'field_ecm_nav_link_is_cta'),
(2, 'nav_links_2_new_tab', '0'),
(2, '_nav_links_2_new_tab','field_ecm_nav_link_new_tab'),

(2, 'nav_links_3_label',   'For Providers'),
(2, '_nav_links_3_label',  'field_ecm_nav_link_label'),
(2, 'nav_links_3_url',     '/for-providers/'),
(2, '_nav_links_3_url',    'field_ecm_nav_link_url'),
(2, 'nav_links_3_is_cta',  '0'),
(2, '_nav_links_3_is_cta', 'field_ecm_nav_link_is_cta'),
(2, 'nav_links_3_new_tab', '0'),
(2, '_nav_links_3_new_tab','field_ecm_nav_link_new_tab'),

(2, 'nav_links_4_label',   'Provider Login'),
(2, '_nav_links_4_label',  'field_ecm_nav_link_label'),
(2, 'nav_links_4_url',     '/provider-dashboard/'),
(2, '_nav_links_4_url',    'field_ecm_nav_link_url'),
(2, 'nav_links_4_is_cta',  '1'),
(2, '_nav_links_4_is_cta', 'field_ecm_nav_link_is_cta'),
(2, 'nav_links_4_new_tab', '0'),
(2, '_nav_links_4_new_tab','field_ecm_nav_link_new_tab'),

-- ── Hero ─────────────────────────────────────────────────────────────────────
(2, 'hero_stamp_arc_top',    '· ALL 50 STATES ·'),
(2, '_hero_stamp_arc_top',   'field_ecm_hero_stamp_arc_top'),
(2, 'hero_stamp_arc_bottom', '· TRUSTED CARE MATCHING ·'),
(2, '_hero_stamp_arc_bottom','field_ecm_hero_stamp_arc_bottom'),
(2, 'hero_stamp_year',       '2002'),
(2, '_hero_stamp_year',      'field_ecm_hero_stamp_year'),

(2, 'hero_title_prefix', 'Find Trusted Elder Care in'),
(2, '_hero_title_prefix','field_ecm_hero_title_prefix'),
(2, 'hero_subtitle',     'One need. One location. Matched in under 2 minutes. Our free care advisor connects you with verified local providers — no spam, no obligation.'),
(2, '_hero_subtitle',    'field_ecm_hero_subtitle'),

(2, 'hero_cta_primary_icon',    '📋'),
(2, '_hero_cta_primary_icon',   'field_ecm_hero_cta_primary_icon'),
(2, 'hero_cta_primary_text',    'Start Your Free Match'),
(2, '_hero_cta_primary_text',   'field_ecm_hero_cta_primary_text'),
(2, 'hero_cta_secondary_icon',  '💬'),
(2, '_hero_cta_secondary_icon', 'field_ecm_hero_cta_secondary_icon'),
(2, 'hero_cta_secondary_text',  'Prefer to chat? Talk to Carrie'),
(2, '_hero_cta_secondary_text', 'field_ecm_hero_cta_secondary_text'),

(2, 'hero_trust_year', '2002'),
(2, '_hero_trust_year','field_ecm_hero_trust_year'),
(2, 'hero_trust_text', 'America\'s oldest & most respected elder care directory · Operating in all 50 states'),
(2, '_hero_trust_text','field_ecm_hero_trust_text'),

-- Hero badges (3)
(2, 'hero_badges',        '3'),
(2, '_hero_badges',       'field_ecm_hero_badges'),
(2, 'hero_badges_0_text', '🔒 Free for Families'),
(2, '_hero_badges_0_text','field_ecm_hero_badge_text'),
(2, 'hero_badges_1_text', '✓ No spam, ever'),
(2, '_hero_badges_1_text','field_ecm_hero_badge_text'),
(2, 'hero_badges_2_text', '⭐ 4.9 avg rating'),
(2, '_hero_badges_2_text','field_ecm_hero_badge_text'),

-- Hero quick categories (5)
(2, 'hero_quick_cats_label', 'Quick start:'),
(2, '_hero_quick_cats_label','field_ecm_hero_quick_cats_label'),

(2, 'hero_quick_cats',          '5'),
(2, '_hero_quick_cats',         'field_ecm_hero_quick_cats'),
(2, 'hero_quick_cats_0_emoji',  '🏠'),
(2, '_hero_quick_cats_0_emoji', 'field_ecm_hero_qcat_emoji'),
(2, 'hero_quick_cats_0_label',  'Home Care'),
(2, '_hero_quick_cats_0_label', 'field_ecm_hero_qcat_label'),
(2, 'hero_quick_cats_0_slug',   'home-care'),
(2, '_hero_quick_cats_0_slug',  'field_ecm_hero_qcat_slug'),

(2, 'hero_quick_cats_1_emoji',  '🏡'),
(2, '_hero_quick_cats_1_emoji', 'field_ecm_hero_qcat_emoji'),
(2, 'hero_quick_cats_1_label',  'Assisted Living'),
(2, '_hero_quick_cats_1_label', 'field_ecm_hero_qcat_label'),
(2, 'hero_quick_cats_1_slug',   'assisted-living'),
(2, '_hero_quick_cats_1_slug',  'field_ecm_hero_qcat_slug'),

(2, 'hero_quick_cats_2_emoji',  '🧠'),
(2, '_hero_quick_cats_2_emoji', 'field_ecm_hero_qcat_emoji'),
(2, 'hero_quick_cats_2_label',  'Memory Care'),
(2, '_hero_quick_cats_2_label', 'field_ecm_hero_qcat_label'),
(2, 'hero_quick_cats_2_slug',   'memory-care'),
(2, '_hero_quick_cats_2_slug',  'field_ecm_hero_qcat_slug'),

(2, 'hero_quick_cats_3_emoji',  '⚖️'),
(2, '_hero_quick_cats_3_emoji', 'field_ecm_hero_qcat_emoji'),
(2, 'hero_quick_cats_3_label',  'Elder Law'),
(2, '_hero_quick_cats_3_label', 'field_ecm_hero_qcat_label'),
(2, 'hero_quick_cats_3_slug',   'elder-law'),
(2, '_hero_quick_cats_3_slug',  'field_ecm_hero_qcat_slug'),

(2, 'hero_quick_cats_4_emoji',  '🕊️'),
(2, '_hero_quick_cats_4_emoji', 'field_ecm_hero_qcat_emoji'),
(2, 'hero_quick_cats_4_label',  'Hospice'),
(2, '_hero_quick_cats_4_label', 'field_ecm_hero_qcat_label'),
(2, 'hero_quick_cats_4_slug',   'hospice'),
(2, '_hero_quick_cats_4_slug',  'field_ecm_hero_qcat_slug'),

-- ── Hero Floating Cards ───────────────────────────────────────────────────────
(2, 'hero_fc_rating_score',  '4.9'),
(2, '_hero_fc_rating_score', 'field_ecm_hero_fc_rating_score'),
(2, 'hero_fc_rating_label',  '12k+ families matched'),
(2, '_hero_fc_rating_label', 'field_ecm_hero_fc_rating_label'),
(2, 'hero_fc_avatar_count',  '+12k'),
(2, '_hero_fc_avatar_count', 'field_ecm_hero_fc_avatar_count'),

(2, 'hero_fc_verified_title', '500+ Verified Providers'),
(2, '_hero_fc_verified_title','field_ecm_hero_fc_verified_title'),
(2, 'hero_fc_verified_sub',   'Pre-screened & trusted'),
(2, '_hero_fc_verified_sub',  'field_ecm_hero_fc_verified_sub'),

(2, 'hero_fc_time_value', '< 2 min'),
(2, '_hero_fc_time_value','field_ecm_hero_fc_time_value'),
(2, 'hero_fc_time_label', 'to your first match · always free'),
(2, '_hero_fc_time_label','field_ecm_hero_fc_time_label'),

-- ── Stats Bar ────────────────────────────────────────────────────────────────
(2, 'stats',   '4'),
(2, '_stats',  'field_ecm_stats'),
(2, 'stats_0_number', '12k+'),
(2, '_stats_0_number','field_ecm_stat_number'),
(2, 'stats_0_label',  'Families matched'),
(2, '_stats_0_label', 'field_ecm_stat_label'),
(2, 'stats_1_number', '500+'),
(2, '_stats_1_number','field_ecm_stat_number'),
(2, 'stats_1_label',  'Verified providers'),
(2, '_stats_1_label', 'field_ecm_stat_label'),
(2, 'stats_2_number', '4.9★'),
(2, '_stats_2_number','field_ecm_stat_number'),
(2, 'stats_2_label',  'Average rating'),
(2, '_stats_2_label', 'field_ecm_stat_label'),
(2, 'stats_3_number', '<2min'),
(2, '_stats_3_number','field_ecm_stat_number'),
(2, 'stats_3_label',  'To get matched'),
(2, '_stats_3_label', 'field_ecm_stat_label'),

-- ── Care Categories ───────────────────────────────────────────────────────────
(2, 'cats_section_tag',      'One need at a time'),
(2, '_cats_section_tag',     'field_ecm_cats_section_tag'),
(2, 'cats_section_title',    'What kind of help do you need in'),
(2, '_cats_section_title',   'field_ecm_cats_section_title'),
(2, 'cats_section_subtitle', 'Select one category — we\'ll instantly show verified local providers and guide you to a free, no-obligation match.'),
(2, '_cats_section_subtitle','field_ecm_cats_section_subtitle'),
(2, 'cats_verified_strip',   'All providers ECM Verified — credential-reviewed & locally licensed since 2002'),
(2, '_cats_verified_strip',  'field_ecm_cats_verified_strip'),

(2, 'categories',   '7'),
(2, '_categories',  'field_ecm_categories'),

(2, 'categories_0_name',         'Home Care'),
(2, '_categories_0_name',        'field_ecm_cat_name'),
(2, 'categories_0_slug',         'home-care'),
(2, '_categories_0_slug',        'field_ecm_cat_slug'),
(2, 'categories_0_icon',         '🏠'),
(2, '_categories_0_icon',        'field_ecm_cat_icon'),
(2, 'categories_0_description',  'In-home aides, personal care, medication management and companionship — so your loved one can stay where they\'re most comfortable.'),
(2, '_categories_0_description', 'field_ecm_cat_description'),
(2, 'categories_0_cta_text',     'See providers in'),
(2, '_categories_0_cta_text',    'field_ecm_cat_cta_text'),

(2, 'categories_1_name',         'Assisted Living'),
(2, '_categories_1_name',        'field_ecm_cat_name'),
(2, 'categories_1_slug',         'assisted-living'),
(2, '_categories_1_slug',        'field_ecm_cat_slug'),
(2, 'categories_1_icon',         '🏡'),
(2, '_categories_1_icon',        'field_ecm_cat_icon'),
(2, 'categories_1_description',  'Residential communities with 24/7 support, social programs, and professional care staff.'),
(2, '_categories_1_description', 'field_ecm_cat_description'),
(2, 'categories_1_cta_text',     'See providers in'),
(2, '_categories_1_cta_text',    'field_ecm_cat_cta_text'),

(2, 'categories_2_name',         'Memory Care'),
(2, '_categories_2_name',        'field_ecm_cat_name'),
(2, 'categories_2_slug',         'memory-care'),
(2, '_categories_2_slug',        'field_ecm_cat_slug'),
(2, 'categories_2_icon',         '🧠'),
(2, '_categories_2_icon',        'field_ecm_cat_icon'),
(2, 'categories_2_description',  'Secure, specialized environments for Alzheimer\'s and dementia with structured daily routines and trained staff.'),
(2, '_categories_2_description', 'field_ecm_cat_description'),
(2, 'categories_2_cta_text',     'See providers in'),
(2, '_categories_2_cta_text',    'field_ecm_cat_cta_text'),

(2, 'categories_3_name',         'Elder Law'),
(2, '_categories_3_name',        'field_ecm_cat_name'),
(2, 'categories_3_slug',         'elder-law'),
(2, '_categories_3_slug',        'field_ecm_cat_slug'),
(2, 'categories_3_icon',         '⚖️'),
(2, '_categories_3_icon',        'field_ecm_cat_icon'),
(2, 'categories_3_description',  'Estate planning, Medicaid guidance, guardianship and legal protection for older adults and their families.'),
(2, '_categories_3_description', 'field_ecm_cat_description'),
(2, 'categories_3_cta_text',     'Find an attorney in'),
(2, '_categories_3_cta_text',    'field_ecm_cat_cta_text'),

(2, 'categories_4_name',         'Care Management'),
(2, '_categories_4_name',        'field_ecm_cat_name'),
(2, 'categories_4_slug',         'care-management'),
(2, '_categories_4_slug',        'field_ecm_cat_slug'),
(2, 'categories_4_icon',         '👩‍💼'),
(2, '_categories_4_icon',        'field_ecm_cat_icon'),
(2, 'categories_4_description',  'Professional care managers coordinate services, navigate healthcare systems and act as your advocate.'),
(2, '_categories_4_description', 'field_ecm_cat_description'),
(2, 'categories_4_cta_text',     'Find a manager in'),
(2, '_categories_4_cta_text',    'field_ecm_cat_cta_text'),

(2, 'categories_5_name',         'Hospice'),
(2, '_categories_5_name',        'field_ecm_cat_name'),
(2, 'categories_5_slug',         'hospice'),
(2, '_categories_5_slug',        'field_ecm_cat_slug'),
(2, 'categories_5_icon',         '🕊️'),
(2, '_categories_5_icon',        'field_ecm_cat_icon'),
(2, 'categories_5_description',  'Compassionate end-of-life support focused on comfort, dignity and family involvement.'),
(2, '_categories_5_description', 'field_ecm_cat_description'),
(2, 'categories_5_cta_text',     'Find hospice care in'),
(2, '_categories_5_cta_text',    'field_ecm_cat_cta_text'),

(2, 'categories_6_name',         'Grief Counselors'),
(2, '_categories_6_name',        'field_ecm_cat_name'),
(2, 'categories_6_slug',         'grief-counselors'),
(2, '_categories_6_slug',        'field_ecm_cat_slug'),
(2, 'categories_6_icon',         '💙'),
(2, '_categories_6_icon',        'field_ecm_cat_icon'),
(2, 'categories_6_description',  'Licensed therapists and counselors specializing in bereavement, loss and caregiver burnout.'),
(2, '_categories_6_description', 'field_ecm_cat_description'),
(2, 'categories_6_cta_text',     'Find support in'),
(2, '_categories_6_cta_text',    'field_ecm_cat_cta_text'),

-- ── How It Works ─────────────────────────────────────────────────────────────
(2, 'hiw_tag',      'Simple Process'),
(2, '_hiw_tag',     'field_ecm_hiw_tag'),
(2, 'hiw_title',    'How It Works'),
(2, '_hiw_title',   'field_ecm_hiw_title'),
(2, 'hiw_subtitle', 'From your first question to a confirmed match — in under 2 minutes.'),
(2, '_hiw_subtitle','field_ecm_hiw_subtitle'),

(2, 'hiw_steps',   '3'),
(2, '_hiw_steps',  'field_ecm_hiw_steps'),

(2, 'hiw_steps_0_number',       '01'),
(2, '_hiw_steps_0_number',      'field_ecm_hiw_step_num'),
(2, 'hiw_steps_0_title',        'Tell us who needs care'),
(2, '_hiw_steps_0_title',       'field_ecm_hiw_step_title'),
(2, 'hiw_steps_0_description',  'Select a care category and enter your location. Takes under 60 seconds — no account required.'),
(2, '_hiw_steps_0_description', 'field_ecm_hiw_step_desc'),

(2, 'hiw_steps_1_number',       '02'),
(2, '_hiw_steps_1_number',      'field_ecm_hiw_step_num'),
(2, 'hiw_steps_1_title',        'We match you instantly'),
(2, '_hiw_steps_1_title',       'field_ecm_hiw_step_title'),
(2, 'hiw_steps_1_description',  'Our system surfaces the top 3 verified, geo-matched providers for your specific need and location.'),
(2, '_hiw_steps_1_description', 'field_ecm_hiw_step_desc'),

(2, 'hiw_steps_2_number',       '03'),
(2, '_hiw_steps_2_number',      'field_ecm_hiw_step_num'),
(2, 'hiw_steps_2_title',        'Connect for free'),
(2, '_hiw_steps_2_title',       'field_ecm_hiw_step_title'),
(2, 'hiw_steps_2_description',  'Review profiles, read real ratings, and connect directly — completely free for families, no spam, no obligation.'),
(2, '_hiw_steps_2_description', 'field_ecm_hiw_step_desc'),

-- ── Why ECM ───────────────────────────────────────────────────────────────────
(2, 'why_tag',   'Why Families Choose Us'),
(2, '_why_tag',  'field_ecm_why_tag'),
(2, 'why_title', 'Built around your urgent need'),
(2, '_why_title','field_ecm_why_title'),

(2, 'why_cards',   '4'),
(2, '_why_cards',  'field_ecm_why_cards'),

(2, 'why_cards_0_icon',         '📍'),
(2, '_why_cards_0_icon',        'field_ecm_why_icon'),
(2, 'why_cards_0_title',        'Geo-aware matching'),
(2, '_why_cards_0_title',       'field_ecm_why_card_title'),
(2, 'why_cards_0_description',  'We only show providers licensed and operating in your city — no out-of-area noise.'),
(2, '_why_cards_0_description', 'field_ecm_why_card_desc'),

(2, 'why_cards_1_icon',         '✓'),
(2, '_why_cards_1_icon',        'field_ecm_why_icon'),
(2, 'why_cards_1_title',        'Verified providers'),
(2, '_why_cards_1_title',       'field_ecm_why_card_title'),
(2, 'why_cards_1_description',  'Every provider is credential-checked, licensed and reviewed by our team before listing.'),
(2, '_why_cards_1_description', 'field_ecm_why_card_desc'),

(2, 'why_cards_2_icon',         '🔒'),
(2, '_why_cards_2_icon',        'field_ecm_why_icon'),
(2, 'why_cards_2_title',        'Free for families'),
(2, '_why_cards_2_title',       'field_ecm_why_card_title'),
(2, 'why_cards_2_description',  'Our service is 100% free to families. Providers subscribe — you never pay a cent.'),
(2, '_why_cards_2_description', 'field_ecm_why_card_desc'),

(2, 'why_cards_3_icon',         '🛡️'),
(2, '_why_cards_3_icon',        'field_ecm_why_icon'),
(2, 'why_cards_3_title',        'Privacy-first'),
(2, '_why_cards_3_title',       'field_ecm_why_card_title'),
(2, 'why_cards_3_description',  'Your contact info is never sold or shared. We connect you directly — no middlemen.'),
(2, '_why_cards_3_description', 'field_ecm_why_card_desc'),

-- ── Testimonials ─────────────────────────────────────────────────────────────
(2, 'testi_tag',      'Trusted by Families'),
(2, '_testi_tag',     'field_ecm_testi_tag'),
(2, 'testi_title',    'What Families Are Saying'),
(2, '_testi_title',   'field_ecm_testi_title'),
(2, 'testi_subtitle', 'Real experiences from caregivers and families across the United States.'),
(2, '_testi_subtitle','field_ecm_testi_subtitle'),

(2, 'testimonials',   '3'),
(2, '_testimonials',  'field_ecm_testimonials'),

(2, 'testimonials_0_stars',    '★★★★★'),
(2, '_testimonials_0_stars',   'field_ecm_testi_stars'),
(2, 'testimonials_0_quote',    'Within 48 hours of using ElderCareMatters, we had three verified home care agencies calling us. The whole process was remarkably simple during an incredibly stressful time.'),
(2, '_testimonials_0_quote',   'field_ecm_testi_quote'),
(2, 'testimonials_0_name',     'Margaret T.'),
(2, '_testimonials_0_name',    'field_ecm_testi_name'),
(2, 'testimonials_0_location', 'Austin, TX'),
(2, '_testimonials_0_location','field_ecm_testi_location'),

(2, 'testimonials_1_stars',    '★★★★★'),
(2, '_testimonials_1_stars',   'field_ecm_testi_stars'),
(2, 'testimonials_1_quote',    'I was overwhelmed trying to find memory care for my father. ECM matched us with a facility that had immediate availability — and it turned out to be perfect for him.'),
(2, '_testimonials_1_quote',   'field_ecm_testi_quote'),
(2, 'testimonials_1_name',     'David R.'),
(2, '_testimonials_1_name',    'field_ecm_testi_name'),
(2, 'testimonials_1_location', 'Seattle, WA'),
(2, '_testimonials_1_location','field_ecm_testi_location'),

(2, 'testimonials_2_stars',    '★★★★★'),
(2, '_testimonials_2_stars',   'field_ecm_testi_stars'),
(2, 'testimonials_2_quote',    'The care advisor answered every question I had and helped me understand what questions to even ask the providers. That guidance was invaluable.'),
(2, '_testimonials_2_quote',   'field_ecm_testi_quote'),
(2, 'testimonials_2_name',     'Patricia L.'),
(2, '_testimonials_2_name',    'field_ecm_testi_name'),
(2, 'testimonials_2_location', 'Miami, FL'),
(2, '_testimonials_2_location','field_ecm_testi_location'),

-- ── FAQ ───────────────────────────────────────────────────────────────────────
(2, 'faq_tag',      'Common Questions'),
(2, '_faq_tag',     'field_ecm_faq_tag'),
(2, 'faq_title',    'Frequently Asked Questions'),
(2, '_faq_title',   'field_ecm_faq_title'),
(2, 'faq_subtitle', 'Everything you need to know before getting started — no pressure, no commitment.'),
(2, '_faq_subtitle','field_ecm_faq_subtitle'),
(2, 'faq_link_text','Browse all FAQs →'),
(2, '_faq_link_text','field_ecm_faq_link_text'),
(2, 'faq_link_url', '/resources/'),
(2, '_faq_link_url','field_ecm_faq_link_url'),

(2, 'faq_items',   '6'),
(2, '_faq_items',  'field_ecm_faq_items'),

(2, 'faq_items_0_question', 'Is ElderCareMatters really free for families?'),
(2, '_faq_items_0_question','field_ecm_faq_q'),
(2, 'faq_items_0_answer',   'Yes — 100% free. We are funded by providers who subscribe to be listed. You never pay a cent, and we never sell your contact information.'),
(2, '_faq_items_0_answer',  'field_ecm_faq_a'),

(2, 'faq_items_1_question', 'How are providers verified?'),
(2, '_faq_items_1_question','field_ecm_faq_q'),
(2, 'faq_items_1_answer',   'Every provider goes through our credential review before being listed — we check state licenses, insurance certificates, and any public complaint records. We also collect ongoing family reviews.'),
(2, '_faq_items_1_answer',  'field_ecm_faq_a'),

(2, 'faq_items_2_question', 'How quickly will I hear from providers?'),
(2, '_faq_items_2_question','field_ecm_faq_q'),
(2, 'faq_items_2_answer',   'Most families receive contact from matched providers within 24 hours. Our care advisors are also available for same-day chat support.'),
(2, '_faq_items_2_answer',  'field_ecm_faq_a'),

(2, 'faq_items_3_question', 'What if I need care in a different city?'),
(2, '_faq_items_3_question','field_ecm_faq_q'),
(2, 'faq_items_3_answer',   'Just click the location badge in the nav and enter a city or ZIP code. Our system will instantly search for verified providers in that area instead.'),
(2, '_faq_items_3_answer',  'field_ecm_faq_a'),

(2, 'faq_items_4_question', 'Can I search for multiple types of care?'),
(2, '_faq_items_4_question','field_ecm_faq_q'),
(2, 'faq_items_4_answer',   'Yes. Each category search is independent. Many families start with home care and then separately research memory care or hospice — you can run as many searches as you need.'),
(2, '_faq_items_4_answer',  'field_ecm_faq_a'),

(2, 'faq_items_5_question', 'What is the 7-step intake form?'),
(2, '_faq_items_5_question','field_ecm_faq_q'),
(2, 'faq_items_5_answer',   'It\'s a brief guided questionnaire that helps us understand your specific care needs — things like urgency, budget range, and any medical requirements. The more context you share, the better we can match you.'),
(2, '_faq_items_5_answer',  'field_ecm_faq_a'),

-- ── Provider CTA ─────────────────────────────────────────────────────────────
(2, 'pcta_tag',      'For Providers'),
(2, '_pcta_tag',     'field_ecm_pcta_tag'),
(2, 'pcta_title',    'Are you an elder care provider?'),
(2, '_pcta_title',   'field_ecm_pcta_title'),
(2, 'pcta_subtitle', 'Join 500+ verified providers already using ElderCareMatters to receive scored, geo-matched leads from families actively searching for your services. Measurable ROI. No guesswork.'),
(2, '_pcta_subtitle','field_ecm_pcta_subtitle'),

(2, 'pcta_primary_text',    'See Plans & Pricing →'),
(2, '_pcta_primary_text',   'field_ecm_pcta_primary_text'),
(2, 'pcta_primary_url',     '/for-providers/'),
(2, '_pcta_primary_url',    'field_ecm_pcta_primary_url'),
(2, 'pcta_secondary_text',  'Provider Login'),
(2, '_pcta_secondary_text', 'field_ecm_pcta_secondary_text'),
(2, 'pcta_secondary_url',   '/provider-dashboard/'),
(2, '_pcta_secondary_url',  'field_ecm_pcta_secondary_url'),

(2, 'pcta_stats',   '3'),
(2, '_pcta_stats',  'field_ecm_pcta_stats'),

(2, 'pcta_stats_0_value', 'Max 3'),
(2, '_pcta_stats_0_value','field_ecm_pcta_stat_val'),
(2, 'pcta_stats_0_label', 'providers per lead'),
(2, '_pcta_stats_0_label','field_ecm_pcta_stat_label'),

(2, 'pcta_stats_1_value', '24h'),
(2, '_pcta_stats_1_value','field_ecm_pcta_stat_val'),
(2, 'pcta_stats_1_label', 'featured exclusive window'),
(2, '_pcta_stats_1_label','field_ecm_pcta_stat_label'),

(2, 'pcta_stats_2_value', '34×'),
(2, '_pcta_stats_2_value','field_ecm_pcta_stat_val'),
(2, 'pcta_stats_2_label', 'average ROI on spend'),
(2, '_pcta_stats_2_label','field_ecm_pcta_stat_label'),

-- ── Footer ────────────────────────────────────────────────────────────────────
(2, 'footer_brand_name', 'ElderCareMatters.com'),
(2, '_footer_brand_name','field_ecm_footer_brand_name'),
(2, 'footer_tagline',    'Connecting families with trusted elder care providers across the United States.'),
(2, '_footer_tagline',   'field_ecm_footer_tagline'),
(2, 'footer_copyright',  '© 2026 ElderCareMatters. All rights reserved.'),
(2, '_footer_copyright', 'field_ecm_footer_copyright'),

(2, 'footer_trust_badges',   '3'),
(2, '_footer_trust_badges',  'field_ecm_footer_trust_badges'),
(2, 'footer_trust_badges_0_icon', '✓'),
(2, '_footer_trust_badges_0_icon','field_ecm_ftb_icon'),
(2, 'footer_trust_badges_0_text', 'Verified Providers'),
(2, '_footer_trust_badges_0_text','field_ecm_ftb_text'),
(2, 'footer_trust_badges_1_icon', '🔒'),
(2, '_footer_trust_badges_1_icon','field_ecm_ftb_icon'),
(2, 'footer_trust_badges_1_text', 'Privacy Protected'),
(2, '_footer_trust_badges_1_text','field_ecm_ftb_text'),
(2, 'footer_trust_badges_2_icon', '⭐'),
(2, '_footer_trust_badges_2_icon','field_ecm_ftb_icon'),
(2, 'footer_trust_badges_2_text', 'Free for Families'),
(2, '_footer_trust_badges_2_text','field_ecm_ftb_text'),

-- Footer columns (3)
(2, 'footer_columns',   '3'),
(2, '_footer_columns',  'field_ecm_footer_columns'),

-- Column 0: Find Care
(2, 'footer_columns_0_title',   'Find Care'),
(2, '_footer_columns_0_title',  'field_ecm_fcol_title'),
(2, 'footer_columns_0_links',   '4'),
(2, '_footer_columns_0_links',  'field_ecm_fcol_links'),
(2, 'footer_columns_0_links_0_text', 'Home Care'),
(2, '_footer_columns_0_links_0_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_0_links_0_url',  '/category/?type=home-care'),
(2, '_footer_columns_0_links_0_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_0_links_1_text', 'Assisted Living'),
(2, '_footer_columns_0_links_1_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_0_links_1_url',  '/category/?type=assisted-living'),
(2, '_footer_columns_0_links_1_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_0_links_2_text', 'Memory Care'),
(2, '_footer_columns_0_links_2_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_0_links_2_url',  '/category/?type=memory-care'),
(2, '_footer_columns_0_links_2_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_0_links_3_text', 'Hospice'),
(2, '_footer_columns_0_links_3_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_0_links_3_url',  '/category/?type=hospice'),
(2, '_footer_columns_0_links_3_url', 'field_ecm_fcol_link_url'),

-- Column 1: Resources
(2, 'footer_columns_1_title',   'Resources'),
(2, '_footer_columns_1_title',  'field_ecm_fcol_title'),
(2, 'footer_columns_1_links',   '4'),
(2, '_footer_columns_1_links',  'field_ecm_fcol_links'),
(2, 'footer_columns_1_links_0_text', 'Elder Care Guides'),
(2, '_footer_columns_1_links_0_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_1_links_0_url',  '/resources/'),
(2, '_footer_columns_1_links_0_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_1_links_1_text', 'Cost of Care'),
(2, '_footer_columns_1_links_1_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_1_links_1_url',  '/resources/'),
(2, '_footer_columns_1_links_1_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_1_links_2_text', 'Dementia Support'),
(2, '_footer_columns_1_links_2_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_1_links_2_url',  '/resources/'),
(2, '_footer_columns_1_links_2_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_1_links_3_text', 'Legal Planning'),
(2, '_footer_columns_1_links_3_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_1_links_3_url',  '/resources/'),
(2, '_footer_columns_1_links_3_url', 'field_ecm_fcol_link_url'),

-- Column 2: Company
(2, 'footer_columns_2_title',   'Company'),
(2, '_footer_columns_2_title',  'field_ecm_fcol_title'),
(2, 'footer_columns_2_links',   '3'),
(2, '_footer_columns_2_links',  'field_ecm_fcol_links'),
(2, 'footer_columns_2_links_0_text', 'For Providers'),
(2, '_footer_columns_2_links_0_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_2_links_0_url',  '/for-providers/'),
(2, '_footer_columns_2_links_0_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_2_links_1_text', 'Provider Login'),
(2, '_footer_columns_2_links_1_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_2_links_1_url',  '/provider-dashboard/'),
(2, '_footer_columns_2_links_1_url', 'field_ecm_fcol_link_url'),
(2, 'footer_columns_2_links_2_text', 'Contact Us'),
(2, '_footer_columns_2_links_2_text','field_ecm_fcol_link_text'),
(2, 'footer_columns_2_links_2_url',  '/contact/'),
(2, '_footer_columns_2_links_2_url', 'field_ecm_fcol_link_url'),

-- Footer bottom bar links
(2, 'footer_bottom_links',   '3'),
(2, '_footer_bottom_links',  'field_ecm_footer_bottom_links'),
(2, 'footer_bottom_links_0_text', 'Free for families'),
(2, '_footer_bottom_links_0_text','field_ecm_fbl_text'),
(2, 'footer_bottom_links_0_url',  '#'),
(2, '_footer_bottom_links_0_url', 'field_ecm_fbl_url'),
(2, 'footer_bottom_links_1_text', 'Verified providers'),
(2, '_footer_bottom_links_1_text','field_ecm_fbl_text'),
(2, 'footer_bottom_links_1_url',  '#'),
(2, '_footer_bottom_links_1_url', 'field_ecm_fbl_url'),
(2, 'footer_bottom_links_2_text', 'No spam guarantee'),
(2, '_footer_bottom_links_2_text','field_ecm_fbl_text'),
(2, 'footer_bottom_links_2_url',  '#'),
(2, '_footer_bottom_links_2_url', 'field_ecm_fbl_url'),

-- ── Modals & Chat ─────────────────────────────────────────────────────────────
(2, 'chat_advisor_name',   'ECM Care Advisor'),
(2, '_chat_advisor_name',  'field_ecm_chat_advisor_name'),
(2, 'chat_advisor_status', 'Online · Avg reply < 1 min'),
(2, '_chat_advisor_status','field_ecm_chat_advisor_status'),
(2, 'chat_avatar_emoji',   '👩‍⚕️'),
(2, '_chat_avatar_emoji',  'field_ecm_chat_avatar_emoji'),
(2, 'dotiq_enabled',       '1'),
(2, '_dotiq_enabled',      'field_ecm_dotiq_enabled'),
(2, 'dotiq_app_id',        'ecm'),
(2, '_dotiq_app_id',       'field_ecm_dotiq_app_id'),

-- ── Location Modal & UI (new fields — seeded alongside PHP field defs) ────────
(2, 'location_modal_title',         'Set your location'),
(2, '_location_modal_title',        'field_ecm_location_modal_title'),
(2, 'location_modal_sub',           'Searching for a parent in a different city? Enter their location.'),
(2, '_location_modal_sub',          'field_ecm_location_modal_sub'),
(2, 'location_modal_city_placeholder', 'City or ZIP code…'),
(2, '_location_modal_city_placeholder','field_ecm_location_modal_city_placeholder'),
(2, 'location_modal_divider',       'or'),
(2, '_location_modal_divider',      'field_ecm_location_modal_divider'),
(2, 'location_modal_cancel',        'Cancel'),
(2, '_location_modal_cancel',       'field_ecm_location_modal_cancel'),
(2, 'location_modal_submit',        'Update Location'),
(2, '_location_modal_submit',       'field_ecm_location_modal_submit'),
(2, 'location_badge_detecting',     'Detecting…'),
(2, '_location_badge_detecting',    'field_ecm_location_badge_detecting'),
(2, 'location_badge_change',        '· Change'),
(2, '_location_badge_change',       'field_ecm_location_badge_change'),

-- Form modal strings
(2, 'form_modal_close_icon',        '×'),
(2, '_form_modal_close_icon',       'field_ecm_form_modal_close_icon'),
(2, 'chat_fab_icon',                '💬'),
(2, '_chat_fab_icon',               'field_ecm_chat_fab_icon'),
(2, 'chat_fab_close_icon',          '×'),
(2, '_chat_fab_close_icon',         'field_ecm_chat_fab_close_icon'),
(2, 'chat_steps_total',             '7'),
(2, '_chat_steps_total',            'field_ecm_chat_steps_total');
